### ISSUE TITLE
Somehow communicate Raw Text changes to Prettier

### ISSUE THREAD

**Issue by sirlantis** [prettier/prettier-swift#1]
There are some syntax combinations that confuse libSyntax leading to a garbage AST.

The two main reasons are semicolons and braces, that can be removed safely:

```
foo(); // can be foo()
```

```
foo { (a) in a } // can be foo { a in a }
```

I scrub the AST once to detect those issues and if so, I clean them up and run `swiftc` again.

However now the `text` that was passed in by `prettier` does not match the actual code anymore and locations might be off. This is especially bad for the comment printer, which sometimes checks for newlines around nodes and it will access invalid locations.

So I need a way to communicate up to prettier that I did some preprocessing on the text.

Right now I have a local modification in `prettier` that finds a secret `__text` property [that I set](https://github.com/prettier/prettier-swift/blob/ac728273356813f03403335123fb0434b011e553/src/parser/index.js#L520) but this doesn't seem clean.

The only better option I can think of now is to have a new optional method on the parser.

```
text = parser.preprocess(text)
ast = parser.parse(text)
```

However that means that I need to parse the AST twice even if it was okay on the first step already.

@azz @vjeux You got any other ideas?

**Comment by vjeux** [comment]
The real solution is to never look at the raw source when printing but instead when parsing we want to annotate the ast with those metadata. For example add a flag saying that there’s an empty line after an expression, or what nodes have comments...

This will be needed if we want to add a way to transform the ast before sending it to prettier.

This is a non trivial refactor though. Adding a way to mutate originalText from the parser is a good workaround for now.

**Comment by sirlantis** [comment]
- Exposed `preprocess` in 3cc6014645df040bff3c14cc9e393dd42cde8eb2
- Created https://github.com/prettier/prettier/pull/3664
- Pointed to the branch for now
