### ISSUE TITLE
Unhandled types

### ISSUE THREAD

**Issue by keith** [prettier/prettier-swift#2]
When running this on our project I discovered some types that aren't currently handled.

- `Backtick`
- `ContinueStmt`
- `DeferStmt`
- `CompositionType`
- `IsTypePattern`

**Comment by sirlantis** [comment]
@keith Awesome, thanks! I'll try to create some tests and a rough implementation for those.

**Comment by keith** [comment]
Awesome thanks! I love the potential of this tool so I'm happy to test any changes on our project!

**Comment by sirlantis** [comment]
@keith These 5 should be supported now. Please consider updating your dependencies as I pointed the prettier dependency to a branch with a hotfix until prettier/prettier#3664 is merged.

**Comment by sirlantis** [comment]
Also, if you see any warnings (except the one regarding "re-writing file") please let me know.

**Comment by keith** [comment]
Awesome thanks I'll try it!
